const {chromium}=require('/tmp/firebird-report-build/node_modules/playwright');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const out=path.join(root,'.impeccable/review');
fs.mkdirSync(out,{recursive:true});
const file=path.join(__dirname,'fly-project-brief.html');
const expectedDownloadHash=JSON.parse(fs.readFileSync(path.join(__dirname,'build-manifest.json'),'utf8')).html_embedded_report_sha256;
const sha256=bytes=>require('node:crypto').createHash('sha256').update(bytes).digest('hex');
const findings={};
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,offline:true,reducedMotion:'reduce'});
  const page=await context.newPage();
  const errors=[],remoteRequests=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(/^https?:/.test(r.url()))remoteRequests.push(r.url());});
  await page.goto(pathToFileURL(file).href);
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('h1').innerText(),'From wiring to a living loop.');
  assert.equal(await page.locator('.repo').count(),96);
  const anchors=await page.locator('a[href^="#"]').evaluateAll(links=>links.map(a=>a.getAttribute('href')).filter(href=>!document.getElementById(href.slice(1))));
  assert.deepEqual(anchors,[],'Every internal anchor must resolve');
  const duplicateIds=await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(el=>el.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);});
  assert.deepEqual(duplicateIds,[]);
  const states=[];
  for(const diet of ['standard','high'])for(const feedback of ['intact','blocked']){
   await page.locator('input[name="diet"][value="'+diet+'"]').check();
   await page.locator('input[name="feedback"][value="'+feedback+'"]').check();
   states.push({diet,feedback,title:await page.locator('#response-title').innerText()});
  }
  assert.equal(new Set(states.map(s=>s.title)).size,4);
  await page.locator('input[name="diet"][value="high"]').check();
  await page.locator('input[name="feedback"][value="intact"]').check();
  await page.locator('#catalog-disclosure>summary').click();
  await page.locator('#repo-category').selectOption('Games and control experiments');
  assert.equal(await page.locator('.repo:not([hidden])').count(),20);
  await page.locator('#repo-search').fill('doomfly');
  assert.equal(await page.locator('.repo:not([hidden])').count(),1);
  await page.locator('.repo:not([hidden])>summary').click();
  assert.match(await page.locator('.repo:not([hidden]) .repo-content').innerText(),/failed visual/);
  await page.locator('#repo-search').fill('not-a-real-fly-repository-xx');
  assert.equal(await page.locator('.repo:not([hidden])').count(),0);
  assert.equal(await page.locator('#empty-state').isVisible(),true);
  await page.locator('#reset-filter').click();
  assert.equal(await page.locator('.repo:not([hidden])').count(),96);
  await page.locator('#repo-category').selectOption('Models, simulation engines and research');
  assert.equal(await page.locator('.repo:not([hidden])').count(),18);
  await page.locator('#reset-filter').click();
  await page.locator('#catalog-disclosure>summary').click();
  const downloadEvent=page.waitForEvent('download');
  await page.locator('[data-download]').first().click();
  const download=await downloadEvent;
  const downloadPath=path.join(out,'downloaded-report.md');
  await download.saveAs(downloadPath);
  assert.equal(sha256(fs.readFileSync(downloadPath)),expectedDownloadHash,'Download must match the report snapshot recorded for this HTML');
  assert.equal(download.suggestedFilename(),'firebird-session-research-report.md');
  findings.states=states;
  findings.viewports=[];
  for(const viewport of [{width:1440,height:1000,name:'desktop'},{width:390,height:844,name:'mobile'}]){
   await page.setViewportSize({width:viewport.width,height:viewport.height});
   await page.evaluate(()=>{document.querySelectorAll('details.repo').forEach(el=>el.open=false);window.scrollTo(0,0);});
   await page.screenshot({path:path.join(out,viewport.name+'.png'),fullPage:true,animations:'disabled'});
   await page.screenshot({path:path.join(out,viewport.name+'-hero.png'),animations:'disabled'});
   await page.locator('#experiment').screenshot({path:path.join(out,viewport.name+'-experiment.png'),animations:'disabled',style:'.masthead{position:static!important}.skip{display:none!important}'});
   const geometry=await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth,fontLoaded:document.fonts.check('600 32px Bricolage'),headingStyle:{font:getComputedStyle(document.querySelector('h1')).fontSize,lineHeight:getComputedStyle(document.querySelector('h1')).lineHeight,spacing:getComputedStyle(document.querySelector('h1')).letterSpacing},responseStyle:{font:getComputedStyle(document.querySelector('#response-title')).fontSize,lineHeight:getComputedStyle(document.querySelector('#response-title')).lineHeight,spacing:getComputedStyle(document.querySelector('#response-title')).letterSpacing},bodyLeading:getComputedStyle(document.body).lineHeight}));
   assert.ok(geometry.scrollWidth<=viewport.width,'No page overflow at '+viewport.width);
   assert.ok(geometry.fontLoaded,'Embedded font loaded');
   findings.viewports.push({...viewport,...geometry});
  }
  await page.setViewportSize({width:320,height:700});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page overflow at 320px');
  await page.setViewportSize({width:1440,height:1000});
  await page.emulateMedia({media:'print'});
  await page.pdf({path:path.join(out,'print-check.pdf'),printBackground:true,preferCSSPageSize:true});
  await page.emulateMedia({media:'screen'});
  await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));
  assert.deepEqual(errors,[]);
  assert.deepEqual(remoteRequests,[],'Standalone report makes no network requests');
  const nojs=await browser.newContext({javaScriptEnabled:false,offline:true,viewport:{width:390,height:844}});
  const fallback=await nojs.newPage();
  await fallback.goto(pathToFileURL(file).href);
  assert.equal(await fallback.locator('.repo').count(),96);
  assert.equal(await fallback.locator('.condition-table tbody tr').count(),2);
  assert.equal(await fallback.locator('.condition-table').isVisible(),true);
  assert.equal(await fallback.locator('[data-download]').first().isVisible(),false);
  await nojs.close();
  findings.result='passed';findings.errors=errors;findings.remoteRequests=remoteRequests;
  findings.checks=['All four evidence states','96 source entries','Category and text filters','Empty and reset states','Native disclosures','Internal anchors and unique IDs','Exact report-snapshot download','Offline with no network requests','Responsive overflow at 320, 390, 1440 pixels','Embedded font','Print-to-PDF generation','No-JavaScript reading fallback'];
  fs.writeFileSync(path.join(__dirname,'verification-results.json'),JSON.stringify(findings,null,2)+'\n');
  console.log(JSON.stringify(findings,null,2));
  await context.close();
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
